<?php ?>
<datalist id="eligible-schools">
<option id='Abbey Green Nursery School & Children's Centre'>Abbey Green Nursery School & Children's Centre</option>
<option id='Allerton Children's Centre'>Allerton Children's Centre</option>
<option id='Barkerend Children's Centre'>Barkerend Children's Centre</option>
<option id='Bierley Children's Centre'>Bierley Children's Centre</option>
<option id='Burnett Fields Children's Centre'>Burnett Fields Children's Centre</option>
<option id='Canterbury Children's Centre'>Canterbury Children's Centre</option>
<option id='Frizinghall and Heaton Village Children's Centre'>Frizinghall and Heaton Village Children's Centre</option>
<option id='Communityworks Children's Centre'>Communityworks Children's Centre</option>
<option id='Bingley Rural Children's Centre'>Bingley Rural Children's Centre</option>
<option id='Crossley Hall Children's Centre'>Crossley Hall Children's Centre</option>
<option id='Fagley Primary School and Children's Centre'>Fagley Primary School and Children's Centre</option>
<option id='Farcliffe & Lilycroft Children and Family Centre'>Farcliffe & Lilycroft Children and Family Centre</option>
<option id='Farnham Rd Children's Centre'>Farnham Rd Children's Centre</option>
<option id='Treetops Children's Centre'>Treetops Children's Centre</option>
<option id='Heaton Primary School & Children's Centre'>Heaton Primary School & Children's Centre</option>
<option id='Highfield Children's Centre'>Highfield Children's Centre</option>
<option id='Hirst Wood Nursery School & Children's Centre'>Hirst Wood Nursery School & Children's Centre</option>
<option id='Holme Wood Children's Centre'>Holme Wood Children's Centre</option>
<option id='Menston and Burley Children's Centre'>Menston and Burley Children's Centre</option>
<option id='Lidget Green Primary School and Children's Centre'>Lidget Green Primary School and Children's Centre</option>
<option id='Low Fold Children and Family Centre'>Low Fold Children and Family Centre</option>
<option id='Midland Road Nursery School and Children's Centre'>Midland Road Nursery School and Children's Centre</option>
<option id='Mortimer House Children's Centre'>Mortimer House Children's Centre</option>
<option id='Owlet Children & Family Centre'>Owlet Children & Family Centre</option>
<option id='Parkland Children's Centre'>Parkland Children's Centre</option>
<option id='Princeville Primary School and Children's Centre'>Princeville Primary School and Children's Centre</option>
<option id='Rainbow Children's Centre'>Rainbow Children's Centre</option>
<option id='Reevy Hill Children's Centre'>Reevy Hill Children's Centre</option>
<option id='Baildon Children's Centre'>Baildon Children's Centre</option>
<option id='Daisy Chain Children's Centre'>Daisy Chain Children's Centre</option>
<option id='St Edmunds Nursery School & Children's Centre'>St Edmunds Nursery School & Children's Centre</option>
<option id='Strong Close Nursery School & Children's Centre'>Strong Close Nursery School & Children's Centre</option>
<option id='Gateway Children's Centre'>Gateway Children's Centre</option>
<option id='Thornton Primary School and Children's Centre'>Thornton Primary School and Children's Centre</option>
<option id='Trinity 5 Rise Children's Centre'>Trinity 5 Rise Children's Centre</option>
<option id='Tyersal Children's Centre'>Tyersal Children's Centre</option>
<option id='Victoria Hall Children's Centre'>Victoria Hall Children's Centre</option>
<option id='Little Lane Children's Centre'>Little Lane Children's Centre</option>
<option id='Woodroyd Children's Centre'>Woodroyd Children's Centre</option>
<option id='Woodside Children's Centre'>Woodside Children's Centre</option>
<option id='Wyke Children's Centre'>Wyke Children's Centre</option>
<option id='Peel Park Primary School and Nursery'>Peel Park Primary School and Nursery</option>
<option id='Strong Close Nursery School'>Strong Close Nursery School</option>
<option id='Hirst Wood Nursery School & Children's Centre'>Hirst Wood Nursery School & Children's Centre</option>
<option id='Lilycroft Nursery School'>Lilycroft Nursery School</option>
<option id='Abbey Green Nursery School & Children's Centre'>Abbey Green Nursery School & Children's Centre</option>
<option id='Midland Road Nursery School'>Midland Road Nursery School</option>
<option id='St Edmund's Nursery School & Children's Centre'>St Edmund's Nursery School & Children's Centre</option>
<option id='Clayton Village Primary School'>Clayton Village Primary School</option>
<option id='Frizinghall Primary School'>Frizinghall Primary School</option>
<option id='Lidget Green Primary School'>Lidget Green Primary School</option>
<option id='Marshfield Primary School'>Marshfield Primary School</option>
<option id='Newby Primary School'>Newby Primary School</option>
<option id='Sandy Lane Primary School'>Sandy Lane Primary School</option>
<option id='Swain House Primary School'>Swain House Primary School</option>
<option id='Thackley Primary School'>Thackley Primary School</option>
<option id='Blakehill Primary School'>Blakehill Primary School</option>
<option id='Wellington Primary School'>Wellington Primary School</option>
<option id='Wibsey Primary School'>Wibsey Primary School</option>
<option id='Bowling Park Primary School'>Bowling Park Primary School</option>
<option id='Stocks Lane Primary School'>Stocks Lane Primary School</option>
<option id='Farfield Primary and Nursery School'>Farfield Primary and Nursery School</option>
<option id='Princeville Primary School'>Princeville Primary School</option>
<option id='Carrwood Primary School'>Carrwood Primary School</option>
<option id='Ley Top Primary School'>Ley Top Primary School</option>
<option id='Grove House Primary School'>Grove House Primary School</option>
<option id='Cavendish Primary School'>Cavendish Primary School</option>
<option id='Worthinghead Primary School'>Worthinghead Primary School</option>
<option id='Poplars Farm Primary School'>Poplars Farm Primary School</option>
<option id='Bankfoot Primary School'>Bankfoot Primary School</option>
<option id='Fagley Primary School'>Fagley Primary School</option>
<option id='Brackenhill Primary School'>Brackenhill Primary School</option>
<option id='Cottingley Village Primary School'>Cottingley Village Primary School</option>
<option id='Crossflatts Primary School'>Crossflatts Primary School</option>
<option id='Eldwick Primary School'>Eldwick Primary School</option>
<option id='Ingrow Primary School'>Ingrow Primary School</option>
<option id='Long Lee Primary School'>Long Lee Primary School</option>
<option id='Oldfield Primary School'>Oldfield Primary School</option>
<option id='Stanbury Village School'>Stanbury Village School</option>
<option id='Saltaire Primary School'>Saltaire Primary School</option>
<option id='Low Ash Primary School'>Low Ash Primary School</option>
<option id='Silsden Primary School'>Silsden Primary School</option>
<option id='Eastburn Junior and Infant School'>Eastburn Junior and Infant School</option>
<option id='Steeton Primary School'>Steeton Primary School</option>
<option id='Ashlands Primary School'>Ashlands Primary School</option>
<option id='Glenaire Primary School'>Glenaire Primary School</option>
<option id='Ben Rhydding Primary School'>Ben Rhydding Primary School</option>
<option id='Hoyle Court Primary School'>Hoyle Court Primary School</option>
<option id='Addingham Primary School'>Addingham Primary School</option>
<option id='Sandal Primary School'>Sandal Primary School</option>
<option id='Girlington Primary School'>Girlington Primary School</option>
<option id='Miriam Lord Community Primary School'>Miriam Lord Community Primary School</option>
<option id='Menston Primary School'>Menston Primary School</option>
<option id='All Saints Church of England Primary School'>All Saints Church of England Primary School</option>
<option id='St Matthew's CofE Primary School and Nursery'>St Matthew's CofE Primary School and Nursery</option>
<option id='St Luke's CofE Primary School'>St Luke's CofE Primary School</option>
<option id='Low Moor CofE Primary School'>Low Moor CofE Primary School</option>
<option id='All Saints' CofE Primary School'>All Saints' CofE Primary School</option>
<option id='Burley and Woodhead CofE Primary School'>Burley and Woodhead CofE Primary School</option>
<option id='St Paul's CofE Primary School'>St Paul's CofE Primary School</option>
<option id='Idle CofE Primary School'>Idle CofE Primary School</option>
<option id='Heaton St Barnabas' CofE Aided Primary School'>Heaton St Barnabas' CofE Aided Primary School</option>
<option id='St Stephen's CofE Primary School'>St Stephen's CofE Primary School</option>
<option id='St Anthony's Catholic Primary School'>St Anthony's Catholic Primary School</option>
<option id='St Clare's Catholic Primary School'>St Clare's Catholic Primary School</option>
<option id='St Columba's Catholic Primary School'>St Columba's Catholic Primary School</option>
<option id='St Joseph's Catholic Primary School'>St Joseph's Catholic Primary School</option>
<option id='St Mary's &St Peter's Catholic Primary School'>St Mary's & St Peter's Catholic Primary School</option>
<option id='St William's Catholic Primary School'>St William's Catholic Primary School</option>
<option id='St Francis Catholic Primary School'>St Francis Catholic Primary School</option>
<option id='Our Lady and St Brendan's Catholic Primary School'>Our Lady and St Brendan's Catholic Primary School</option>
<option id='St Cuthbert and The First Martyrs' Catholic Primary School'>St Cuthbert and The First Martyrs' Catholic Primary School</option>
<option id='St Matthew's Catholic Primary School'>St Matthew's Catholic Primary School</option>
<option id='Baildon CofE Primary School'>Baildon CofE Primary School</option>
<option id='Trinity All Saints CofE VA Primary School'>Trinity All Saints CofE VA Primary School</option>
<option id='Keighley St Andrew's CofE Primary School and Nursery'>Keighley St Andrew's CofE Primary School and Nursery</option>
<option id='Riddlesden St Mary's CofE Primary School'>Riddlesden St Mary's CofE Primary School</option>
<option id='St Joseph's Catholic Primary School'>St Joseph's Catholic Primary School</option>
<option id='St Anthony's Catholic Primary School'>St Anthony's Catholic Primary School</option>
<option id='Titus Salt School'>Titus Salt School</option>
<option id='Carlton Bolling College'>Carlton Bolling College</option>
<option id='The Holy Family Catholic School'>The Holy Family Catholic School</option>
<option id='Killinghall Primary School'>Killinghall Primary School</option>
<option id='Foxhill Primary School'>Foxhill Primary School</option>
<option id='Russell Hall Primary School'>Russell Hall Primary School</option>
<option id='Hill Top CofE Primary School'>Hill Top CofE Primary School</option>
<option id='Myrtle Park Primary School'>Myrtle Park Primary School</option>
<option id='Keelham Primary School'>Keelham Primary School</option>
<option id='Bingley Grammar School'>Bingley Grammar School</option>
<option id='Hanson School'>Hanson School</option>
<option id='Netherleigh and Rossefield School'>Netherleigh and Rossefield School</option>
<option id='Ghyll Royd School and Pre-School'>Ghyll Royd School and Pre-School</option>
<option id='Moorfield School'>Moorfield School</option>
<option id='Westville House School'>Westville House School</option>
<option id='Bradford Grammar School'>Bradford Grammar School</option>
<option id='Lady Lane Park School'>Lady Lane Park School</option>
<option id='Jaamiatul Imaam Muhammad Zakaria'>Jaamiatul Imaam Muhammad Zakaria</option>
<option id='Bradford Christian School'>Bradford Christian School</option>
<option id='Olive Secondary Boys'>Olive Secondary Boys</option>
<option id='Bradford College'>Bradford College</option>
<option id='Shipley College'>Shipley College</option>
<option id='Crystal Gardens Primary School'>Crystal Gardens Primary School</option>
<option id='Dixons City Academy'>Dixons City Academy</option>
<option id='Tracks'>Tracks</option>
<option id='Home Farm Primary School'>Home Farm Primary School</option>
<option id='Thorpe Primary School'>Thorpe Primary School</option>
<option id='Knowleswood Primary School'>Knowleswood Primary School</option>
<option id='Newhall Park Primary School'>Newhall Park Primary School</option>
<option id='Parkside School'>Parkside School</option>
<option id='Burley Oaks Primary School'>Burley Oaks Primary School</option>
<option id='Canterbury Nursery School and Centre for Children and Families'>Canterbury Nursery School and Centre for Children and Families</option>
<option id='Primary Pupil Referral Unit'>Primary Pupil Referral Unit</option>
<option id='Bradford Central PRU'>Bradford Central PRU</option>
<option id='Islamic Tarbiyah Preparatory School'>Islamic Tarbiyah Preparatory School</option>
<option id='The Home Study Project Co Pakistan Community and Neighbourhood Assoc'>The Home Study Project Co Pakistan Community and Neighbourhood Assoc</option>
<option id='Education In Hospital 2 (BRI)'>Education In Hospital 2 (BRI)</option>
<option id='Education In Hospital 1 (Airedale)'>Education In Hospital 1 (Airedale)</option>
<option id='University of Bradford'>University of Bradford</option>
<option id='Lister Primary School'>Lister Primary School</option>
<option id='Darul Uloom Dawatul Imaan'>Darul Uloom Dawatul Imaan</option>
<option id='TLG Bradford'>TLG Bradford</option>
<option id='Al Mumin Primary and Secondary School'>Al Mumin Primary and Secondary School</option>
<option id='The Fountain'>The Fountain</option>
<option id='Chellow Heights Special School'>Chellow Heights Special School</option>
<option id='Beechcliffe Special School'>Beechcliffe Special School</option>
<option id='Delius Special School'>Delius Special School</option>
<option id='Bradford Academy'>Bradford Academy</option>
<option id='Bradford District PRU'>Bradford District PRU</option>
<option id='Dixons Allerton Academy'>Dixons Allerton Academy</option>
<option id='Eternal Light Secondary School'>Eternal Light Secondary School</option>
<option id='University Academy Keighley'>University Academy Keighley</option>
<option id='Ilkley Grammar School'>Ilkley Grammar School</option>
<option id='Feversham Academy'>Feversham Academy</option>
<option id='Dixons Kings Academy'>Dixons Kings Academy</option>
<option id='Rainbow Primary School'>Rainbow Primary School</option>
<option id='Ellar Carr'>Ellar Carr</option>
<option id='Prism Independent School'>Prism Independent School</option>
<option id='Belle Vue Girls' Academy'>Belle Vue Girls' Academy</option>
<option id='Oastlers School'>Oastlers School</option>
<option id='Dixons Trinity Academy'>Dixons Trinity Academy</option>
<option id='Dixons Music Primary'>Dixons Music Primary</option>
<option id='Ryecroft Primary Academy'>Ryecroft Primary Academy</option>
<option id='Feversham Primary Academy'>Feversham Primary Academy</option>
<option id='St Oswald's Church of England Primary Academy'>St Oswald's Church of England Primary Academy</option>
<option id='Whetley Academy'>Whetley Academy</option>
<option id='Christ Church Church of England Academy'>Christ Church Church of England Academy</option>
<option id='Merlin Top Primary Academy'>Merlin Top Primary Academy</option>
<option id='The Sacred Heart Catholic Primary School'>The Sacred Heart Catholic Primary School</option>
<option id='Shibden Head Primary Academy'>Shibden Head Primary Academy</option>
<option id='One In A Million Free School'>One In A Million Free School</option>
<option id='Beckfoot School'>Beckfoot School</option>
<option id='Hazelbeck Special School'>Hazelbeck Special School</option>
<option id='Southfield School'>Southfield School</option>
<option id='Grange Technology College'>Grange Technology College</option>
<option id='Oasis Academy Lister Park'>Oasis Academy Lister Park</option>
<option id='Harden Primary School'>Harden Primary School</option>
<option id='Iqra Academy'>Iqra Academy</option>
<option id='Bradford Girls' Grammar School'>Bradford Girls' Grammar School</option>
<option id='Dixons Marchbank Primary'>Dixons Marchbank Primary</option>
<option id='Bradford Forster Academy'>Bradford Forster Academy</option>
<option id='J.A.M.E.S'>J.A.M.E.S</option>
<option id='St Bede's and St Joseph's Catholic College'>St Bede's and St Joseph's Catholic College</option>
<option id='Shirley Manor Primary School'>Shirley Manor Primary School</option>
<option id='Dixons McMillan Academy'>Dixons McMillan Academy</option>
<option id='Our Lady of Victories Catholic School'>Our Lady of Victories Catholic School</option>
<option id='St Anne's Catholic Primary School'>St Anne's Catholic Primary School</option>
<option id='St Philip's CofE Primary School'>St Philip's CofE Primary School</option>
<option id='Southmere Primary Academy'>Southmere Primary Academy</option>
<option id='Dixons Manningham Academy'>Dixons Manningham Academy</option>
<option id='Training and Skills Centre'>Training and Skills Centre</option>
<option id='Beckfoot Upper Heaton'>Beckfoot Upper Heaton</option>
<option id='High Crags Primary Leadership Academy'>High Crags Primary Leadership Academy</option>
<option id='Immanuel College'>Immanuel College</option>
<option id='Laisterdyke Leadership Academy'>Laisterdyke Leadership Academy</option>
<option id='Tong Leadership Academy'>Tong Leadership Academy</option>
<option id='Broadbeck Learning Centre'>Broadbeck Learning Centre</option>
<option id='Westminster Church of England Primary Academy'>Westminster Church of England Primary Academy</option>
<option id='Buttershaw Business & Enterprise College Academy'>Buttershaw Business & Enterprise College Academy</option>
<option id='Barkerend Primary Leadership Academy'>Barkerend Primary Leadership Academy</option>
<option id='St John the Evangelist Catholic Primary School'>St John the Evangelist Catholic Primary School</option>
<option id='Oxenhope CofE Primary School'>Oxenhope CofE Primary School</option>
<option id='St Walburga's Catholic Primary School, A Voluntary Academy'>St Walburga's Catholic Primary School, A Voluntary Academy</option>
<option id='Oakworth Primary School'>Oakworth Primary School</option>
<option id='Haworth Primary School'>Haworth Primary School</option>
<option id='Lees Primary School'>Lees Primary School</option>
<option id='St Winefride's Catholic Primary School, A Voluntary Academy'>St Winefride's Catholic Primary School, A Voluntary Academy</option>
<option id='St Joseph's Catholic Primary School'>St Joseph's Catholic Primary School</option>
<option id='Beckfoot Allerton Primary School and Nursery'>Beckfoot Allerton Primary School and Nursery</option>
<option id='Horton Grange Primary School'>Horton Grange Primary School</option>
<option id='Beckfoot Heaton Primary'>Beckfoot Heaton Primary</option>
<option id='Horton Park Primary School'>Horton Park Primary School</option>
<option id='Copthorne Primary School'>Copthorne Primary School</option>
<option id='Beckfoot Oakbank'>Beckfoot Oakbank</option>
<option id='Queensbury Academy'>Queensbury Academy</option>
<option id='Beckfoot Thornton'>Beckfoot Thornton</option>
<option id='Worth Valley Primary School'>Worth Valley Primary School</option>
<option id='Reevy Hill Primary School'>Reevy Hill Primary School</option>
<option id='High Park School'>High Park School</option>
<option id='Lapage Primary School and Nursery'>Lapage Primary School and Nursery</option>
<option id='Atlas Community Primary School'>Atlas Community Primary School</option>
<option id='Westbourne Primary School'>Westbourne Primary School</option>
<option id='Denholme Primary School'>Denholme Primary School</option>
<option id='Margaret McMillan Primary School'>Margaret McMillan Primary School</option>
<option id='Parkwood Primary School'>Parkwood Primary School</option>
<option id='Victoria Primary School'>Victoria Primary School</option>
<option id='Lilycroft Primary School'>Lilycroft Primary School</option>
<option id='Green Lane Primary School'>Green Lane Primary School</option>
<option id='The Academy At St. James'>The Academy At St. James</option>
<option id='Thornton Primary School'>Thornton Primary School</option>
<option id='Holycroft Primary School'>Holycroft Primary School</option>
<option id='Wilsden Primary School'>Wilsden Primary School</option>
<option id='Byron Primary School'>Byron Primary School</option>
<option id='Woodside Academy'>Woodside Academy</option>
<option id='Hollingwood Primary School'>Hollingwood Primary School</option>
<option id='Laycock Primary School'>Laycock Primary School</option>
<option id='Farnham Primary School'>Farnham Primary School</option>
<option id='Beckfoot Priestthorpe Primary School & Nursery'>Beckfoot Priestthorpe Primary School & Nursery</option>
<option id='Beckfoot Phoenix'>Beckfoot Phoenix</option>
<option id='East Morton CofE Primary School'>East Morton CofE Primary School</option>
<option id='Olive Secondary Girls'>Olive Secondary Girls</option>
<option id='Appleton Academy'>Appleton Academy</option>
<option id='Clayton St John CofE Primary School'>Clayton St John CofE Primary School</option>
<option id='St John's CofE Primary School'>St John's CofE Primary School</option>
<option id='Woodlands Church of England Primary Academy'>Woodlands Church of England Primary Academy</option>
<option id='Holybrook Primary School'>Holybrook Primary School</option>
<option id='The Co-op Academy Parkland'>The Co-op Academy Parkland</option>
<option id='Thornbury Primary Leadership Academy'>Thornbury Primary Leadership Academy</option>
<option id='Cullingworth Village Primary School'>Cullingworth Village Primary School</option>
<option id='Dixons Cottingley Academy'>Dixons Cottingley Academy</option>
<option id='Eastwood Community School'>Eastwood Community School</option>
<option id='Beckfoot Nessfield'>Beckfoot Nessfield</option>
<option id='Fearnville Primary School'>Fearnville Primary School</option>
<option id='Wycliffe CofE Primary School'>Wycliffe CofE Primary School</option>
<option id='Shipley CofE Primary School'>Shipley CofE Primary School</option>
<option id='Crossley Hall Primary School'>Crossley Hall Primary School</option>
<option id='Lower Fields Primary Academy'>Lower Fields Primary Academy</option>
    <option id='Montgomery High School'>Montgomery High School</option>
    <option id='St Marys Catholic Academy'>St Mary's Catholic Academy</option>
    <option id='Cowley International College'>Cowley International College</option>
    <option id='Hall Cross Academy'>Hall Cross Academy</option>
    <option id='Castleford Academy'>Castleford Academy</option>
    <option id='Brine Leas'>Brine Leas</option>
    <option id='Broadland High Ormiston Academy'>Broadland High Ormiston Academy</option>
</datalist>
